In [18]:
%cd /home/jack/projects/customer_churn_model/
from pycaret.classification import *
import mlflow

from src.data.load_data import read_params

# load in config params
config = read_params(config_path="params.yaml")
data_path = config["raw_data_config"]["raw_data_fold_csv"]
target = config["raw_data_config"]["target"]
# read training data
df = pd.read_csv(data_path)

# target mapping
target_mapping = {"no": 0, "yes": 1}
df.loc[:, target] = df[target].map(target_mapping)

clf1 = setup(df, target = target, log_experiment= True, experiment_name= "mlflow/churn_model")

In [23]:
# compare all baseline models and select top 5
top5 = compare_models(n_select = 5, sort = "AUC")

In [24]:
# tune top 5 base models
tuned_top5 = [tune_model(i) for i in top5]